Models/Atleta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Atleta
    {
        public int AtletaID { get; set; }
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }
        public bool Profissional { get; set; }

        //Relacionamentos
        public IList<CorridaAtleta> CorridaAtletas { get; set; }

    }
}

Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public enum Categoria
    {
        Pista, Rua, Esteira
    }
}

Models/CategoriaMedalha.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public enum CategoriaMedalha
    {
        Participacao, Ouro, Prata, Bronze
    }
}

Models/Corrida.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CorridaFiapWebAsp.Models
{
    public class Corrida
    {
        public int CorridaId { get; set; }
        public string Nome { get; set; }
        public float Distancia { get; set; }
        public bool Premiacao { get; set; }
        public Categoria Categoria { get; set; }

        // Relacionamento
        public Trajeto Trajeto { get; set; }
    }
}

Models/CorridaAtleta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class CorridaAtleta
    {
        public Corrida Corrida { get; set; }
        public int CorridaId { get; set; }
        public Atleta Atleta { get; set; }
        public int AtletaId { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace _06_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Medalha.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Medalha
    {
        public int MedalhaId { get; set; }
        public CategoriaMedalha Categoria { get; set; }
        public float Peso { get; set; }
        public int Quantidade { get; set; }

        //Relacionamentos
        public Corrida Corrida { get; set; }
        public int CorridaId { get; set; }
    }
}

Models/Trajeto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Trajeto
    {
        public int TrajetoId { get; set; }
        public float Distancia { get; set; }
        public string LocalInicio { get; set; }

    }
}

Controllers/CorridaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _06_Fiap.Web.AspNet.Models;
using _06_Fiap.Web.AspNet.Persistences;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class CorridaController : Controller
    {
        private RacerContext _context;

        public CorridaController(RacerContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Pesquisar(string termoPesquisa)
        {
            var lista = _context.Corridas
                .Where(c => c.Nome.Contains(termoPesquisa)).Include(c => c.Trajeto).ToList();
            //retorna para a página Listar com a lista filtrada
            return View("Listar",lista);
        }

        [HttpPost]
        public IActionResult Excluir(int codigo)
        {
            var corrida = _context.Corridas.Find(codigo);
            _context.Corridas.Remove(corrida);
            _context.SaveChanges();
            TempData["mensagem"] = "Removido!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            return View(_context.Corridas.Find(id));
        }

        [HttpPost]
        public IActionResult Editar(Corrida corrida)
        {
            _context.Corridas.Update(corrida);
            _context.SaveChanges();
            TempData["mensagem"] = "Atualizado!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Listar()
        {
            //Include - inclui o relacionamento na pesquisa
            return View(_context.Corridas.Include(c => c.Trajeto).ToList());
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Corrida corrida)
        {
            _context.Corridas.Add(corrida);
            _context.SaveChanges();
            TempData["mensagem"] = "Cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _06_Fiap.Web.AspNet.Models;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Corrida/Cadastrar.cshtml
@model  Corrida

@{
    ViewData["Title"] = "Cadastrar";
}

<h2>Cadastrar</h2>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="Cadastrar" asp-controller="Corrida">
    <partial name="_formulario"/>
    <input type="submit" class="btn btn-primary" value="Cadastrar" />
</form>

Views/Corrida/Editar.cshtml
@model  Corrida

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar</h2>

<form asp-action="editar" asp-controller="corrida">
    <input asp-for="CorridaId" />
    <partial name="_formulario"/>
    <input value="Editar" class="btn btn-primary" type="submit"/>
</form>

Views/Corrida/Listar.cshtml
@model IList<Corrida>

@{
    ViewData["Title"] = "Listar";
}

<h2>Listar</h2>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="pesquisar" method="get" class="form-inline">
    <input placeholder="Digite o nome" name="termoPesquisa" type="text" class="form-control"/>
    <input type="submit" value="Pesquisar" class="btn btn-success" />
</form>
<br />
<table class="table">
    <tr>
        <th>Nome</th>
        <th>Distancia</th>
        <th>Premiação</th>
        <th>Categoria</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Distancia</td>
            <td>@(item.Premiacao ? "Sim" : "Não")</td>
            <td>@item.Categoria</td>
            <td>
                <a class="btn btn-primary btn-sm" asp-action="editar" asp-route-id="@item.CorridaId">Editar</a>
                <!-- Botão para acionar modal -->
                <button onclick="codigo.value = @item.CorridaId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalExemplo">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>



<!-- Modal -->
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir?
            </div>
            <div class="modal-footer">
                <form asp-action="excluir">
                    <input name="codigo" type="hidden" id="codigo" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Corrida/_formulario.cshtml
@model Corrida

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Distancia"></label>
    <input asp-for="Distancia" class="form-control" />
</div>
<div class="form-group">
    <input asp-for="Premiacao" />
    <label asp-for="Premiacao"></label>
</div>
<div class="form-group">
    <label asp-for="Trajeto.LocalInicio"></label>
    <input asp-for="Trajeto.LocalInicio" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Trajeto.Distancia"></label>
    <input asp-for="Trajeto.Distancia" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Categoria"></label>
    <select asp-for="Categoria" class="form-control"
            asp-items="@Html.GetEnumSelectList<Categoria>()">
        <option>Selecione</option>
    </select>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FIAP | @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FIAP Run</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Corrida" asp-action="Cadastrar">Cadastrar</a></li>
                    <li><a asp-area="" asp-controller="Corrida" asp-action="Listar">Corridas</a></li>                    
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FIAP Run</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>